# Generated by Django 6.1 on 2026-08-31 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('celular', models.CharField(max_length=10)),
                ('documento', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('documento', models.CharField(max_length=20)),
                ('celular', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=40)),
                ('nombre', models.CharField(max_length=100)),
                ('cargo', models.CharField(choices=[('costr', 'Costurero'), ('tapcr', 'Tapicero'), ('gerente', 'Gerente'), ('secre', 'Secretario')], default='tapcr', max_length=10)),
                ('celular', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edad', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('tareas_realizadas', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descripcion', models.CharField(max_length=1000)),
                ('codigo_producto', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='AnalisisFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuentes_ingresos', models.DecimalField(decimal_places=2, max_digits=12)),
                ('productos_vendidos', models.IntegerField()),
                ('id_administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.administrador')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=6)),
                ('fecha_creacion', models.DateField()),
                ('hora_creacion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('evidencias', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=1000)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.empleado')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('nombre_mes', models.CharField(max_length=20)),
                ('dia', models.IntegerField()),
                ('nombre_dia', models.CharField(max_length=20)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_creacion', models.TimeField()),
                ('fecha_creacion', models.DateField()),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.empleado')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Catalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.CharField(max_length=100)),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.inventario')),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.producto')),
            ],
        ),
        migrations.CreateModel(
            name='TareasPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20)),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanview.tareaspedido')),
            ],
        ),
    ]
