# Generated by Django 6.1 on 2026-09-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='cliente',
            name='token',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='cliente',
            name='url_valida',
            field=models.BooleanField(default=False),
        ),
    ]
